### ISSUE TITLE
Request - Change angle of set angle key

### ISSUE THREAD

**Issue by InstantVertigo** [millionart/PhotoshopBrushRotateTool#10]
I would like to be able to change the angle so I'll be able to flip my brush 180 degrees with a single button.

**Comment by millionart** [comment]
Try holding down B and hovering to move the brush then releasing B.
The angular direction of the moving brush determines the angle of the brush rotation

**Comment by InstantVertigo** [comment]
This feature is great, but I would also love to have it with a single button without the swipe. 
What I thought about is an option an the Config.ini to be able to change how much "addAngleKey=;" adds (instead of ~10 degrees change to 180).
I don't know if that's possible or if there's an easier way. Anyway love your programs! been using Apssistant for a long time :)
