### ISSUE TITLE
Brush rotation is not working

### ISSUE THREAD

**Issue by Mihaicii** [millionart/PhotoshopBrushRotateTool#2]
Neither the B button and the ; ' are not working. As the previous Issue owner said they just flash the brush panel. Basically i have the same issue as him.

Is there a specific directory where i have to install the Brush Rotate Tool, or can i install it anywhere?

I'm on Windows 10 Home, Photoshop CC and working on a Cintiq 27 if this information helps.

Thank you!

**Comment by millionart** [comment]
Please try the following methods to solve:

1. Run as administrator.
2. Unplug the tablet and use only the keyboard and mouse (this will help troubleshoot the tablet).
3. Update the system patch (enter Win+X and then Y, tell me your operating system version, for example 17763.253).

Please tell me if there are any changes after these operations.
I don't have a Cintiq or any pen display, so I can't confirm whether it's related to this.

**Comment by Mihaicii** [comment]
Hi,

I tried the methods above but it's still not working, so it's not the tablet. 
Updated to OS version 17763.292 but the problem is the same (when i release any of the buttons used for brush rotate they just flash the brush panel).

**Comment by millionart** [comment]
Can you record a video?

**Comment by Mihaicii** [comment]
Sorry but i can't record a video.
It's nothing special about the brush panel flashing, it's just doing what you specified in the Q & A in the Gumroad descriptions of the product. Only that the brush is not rotating.

"The right click menu on the screen flashes each time the brush is rotated?
The right-click menu flashes to indicate that the program is worked fine. This tool actually replaces the manual rotation of the brush."

**Comment by millionart** [comment]
1. Open photoshop
2. New canvas
3. Brush mode
4. Right click on the canvas and keep the menu display status
5. Screenshot and post png here

At least I want to see if your version of Photoshop might differ from me.

**Comment by millionart** [comment]
Are you using multiple monitors? Is it normal to try to use a single monitor?

**Comment by Mihaicii** [comment]
I only use one display.

![img](https://user-images.githubusercontent.com/47223370/52090001-bf960180-25b8-11e9-88b4-1a31ee5a4e78.png)

Here is the screenshot, hope it helps.

**Comment by Mihaicii** [comment]
Photoshop is the latest one, i just updated it today. Latest CC.

**Comment by millionart** [comment]
This is too strange, can you package your configuration file to me?
`%AppData%\Adobe\Adobe Photoshop CC 2019\Adobe Photoshop CC 2019 Settings`

**Comment by Mihaicii** [comment]
You mean to package all the files in the \Adobe Photoshop CC 2019 Settings?

**Comment by millionart** [comment]
Yes, I have to restore your software environment as much as possible.

**Comment by Mihaicii** [comment]
The RAR Archive has 130MB how can i send it to you?

**Comment by millionart** [comment]
Try 
https://send.firefox.com/
https://www.file.io/
https://send-anywhere.com/
or dropbox, google drive, box ect.

**Comment by millionart** [comment]
I just released a new version to fix the bug. Please download the 1.4 version to try.

**Comment by Mihaicii** [comment]
Hi, YES!!! THANK YOU!! :)
It's working now.

This really helps a lot! I will spread the word about your app, i'm sure many will find this helpful.

**Comment by Mihaicii** [comment]
If i find other issues with it, i will post them here.
