### ISSUE TITLE
Brush Rotation issue

### ISSUE THREAD

**Issue by toakui** [millionart/PhotoshopBrushRotateTool#8]
Hi, like the last person I have the same issue with the brush rotation. It wont rotate, it will only flash the brush preset tab. Do you have a fix for this? thanks

**Comment by millionart** [comment]
This issue should have been fixed in the latest version 1.5. I have not received similar feedback in recent months. Can you give me your version number, including brush rotation tool, operating system, photoshop version?
If possible, please record a video to help me confirm the problem.

**Comment by toakui** [comment]
I figured it out, sorry. it's working now
